apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId 'com.ficc.mwmovil'
        minSdkVersion 20 //29
        targetSdkVersion 33
        multiDexEnabled true
        versionCode 248
        versionName "1.3.5"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('progu' +
                    'ard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        checkReleaseBuilds false
    }
    buildToolsVersion '33.0.0'
 //   compileOptions {
  //      sourceCompatibility JavaVersion.VERSION_1_6
  //      targetCompatibility JavaVersion.VERSION_1_6
  //  }
    sourceSets.main {
        jniLibs.srcDir 'src/main/libs'
        //disable automatic ndk-build call
    }
    /*
    packagingOptions {
        exclude 'lib/armeabi-v7a/libPdf417Mobi.so'
        exclude 'lib/x86/libPdf417Mobi.so'
        exclude 'lib/arm64-v8a/libPdf417Mobi.so'
        exclude 'lib/x86_64/libPdf417Mobi.so'

        exclude 'lib/x86/libPdf417Mobi.so'
        exclude 'lib/armeabi/libPdf417Mobi.so'
        exclude 'lib/armeabi-v7a/libPdf417Mobi.so'
        exclude 'lib/x86/libPdf417Mobi.so'
        exclude 'lib/arm64-v8a/libPdf417Mobi.so'
        exclude 'lib/x86_64/libPdf417Mobi.so'
        exclude 'lib/mips/libPdf417Mobi.so'
        exclude 'lib/mips64/libPdf417Mobi.so'

    }
    */

/*
    productFlavors {
    x86 {
        ndk {
            abiFilter "x86"
        }
    }
    armv7 {
        ndk {
            abiFilter "armeabi-v7a"
        }
    }
    arm {
        ndk {
            abiFilter "armeabi"
        }
    }
}
*/




    dynamicFeatures = []
    buildFeatures {
        viewBinding true
    }
    namespace 'com.ficc.mwmovil'
}

dependencies {


    implementation fileTree(include: ['*.jar'], dir: 'libs')
//noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    //  implementation 'com.google.zxing:android-core:3.4.0'
    //  implementation 'com.google.zxing:android-core:3.3.2'
// https://mvnrepository.com/artifact/com.itextpdf/itextpdf
    implementation group: 'com.itextpdf', name: 'itextpdf', version: '5.5.13.4'

    //noinspection GradleCompatible
//    implementation 'com.android.support:appcompat-v7:23.4.0'
    //implementation 'com.google.android.gms:play-services:7.8+' -- comentado para subir a play store
    //implementation 'com.google.android.gms:play-services-location:19.4.0'
    //-- comentado para subir a play store
    // implementation 'com.android.support:multidex:1.0.3'
//noinspection GradleCompatible
    implementation 'com.android.support.constraint:constraint-layout:2.0.4'
    implementation 'android.arch.lifecycle:livedata:1.1.1'
    implementation 'android.arch.lifecycle:viewmodel:1.1.1'
    implementation 'android.arch.navigation:navigation-fragment:1.0.0'
    implementation 'android.arch.navigation:navigation-ui:1.0.0'
    implementation 'com.android.support:design:28.0.0'

   // implementation 'com.sun.mail:android-mail:1.6.7'
    implementation 'com.sun.mail:android-activation:1.6.7'

    implementation files('libs/mysql-connector-java-5.1.8-bin.jar')
    implementation 'com.android.support:support-vector-drawable:28.0.0'
    testImplementation 'junit:junit:4.13.2'
    //androidTestImplementation 'com.android.support.test:runner:1.0.2' -- se comento
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
//     implementation 'com.android.support:design:27.1.1'
    //implementation 'com.android.support:design:28.0.0' - se comento
    //implementation 'com.android.support:design:23.4.0'
    //implementation 'com.android.support:design:22.2.1'
    compileOnly files('libs/httpmime-4.2.5.jar')
    //implementation 'com.google.android.gms:play-services-maps:16.1.0'  -- comentado para subir a play store


//api 'me.dm7.barcodescanner:zxing:1.8.4'

    //api 'me.dm7.barcodescanner:zxing:1.9.8'
    //compile 'com.itextpdf:root:7.0.0'


    //api 'me.dm7.barcodescanner:zxing:1.9.13'  //temp

    implementation 'com.itextpdf:itext7-core:7.2.5'
    //api 'me.dm7.barcodescanner:zxing:3.3.2'
    compileOnly files('libs/sdt-brc-android-natives.jar')
    compileOnly files('libs/sdt-brc-android.jar')
//  api 'com.google.android.gms:play-services:7.8+'
    //   implementation('com.microblink:pdf417.mobi:7.2.0@aar') {
    //       transitive = true
    //   }

}
